### ISSUE TITLE
C# missing

### ISSUE THREAD

**Issue by juamar** [heremaps/flexible-polyline#10]
Will be nice to have C# Class/code in order to work with this.

**Comment by lene** [comment]
Hi, thank you for your interest! Since C# support is currently not planned, I'll leave the issue open in the hope that somebody is interest in implementing this.

**Comment by TonyLugg** [comment]
I would like a C# version too.  Should be pretty similar to Java, but is a bit complicated.

**Comment by TonyLugg** [comment]
Can't move to V8 routing without a .NET version of the decoder.

**Comment by dhippo78** [comment]
This version of the decoder I converted, I use without any issues: [https://github.com/dhippo78/flexible-polyline/commit/43520ad22d8912fbcb80a77a532ef3bbfbbde171](url)

**Comment by dhippo78** [comment]
This version of the decoder I converted, I use without any issues: https://github.com/dhippo78/flexible-polyline/commit/43520ad22d8912fbcb80a77a532ef3bbfbbde171

**Comment by lene** [comment]
Closed by PR #31
