### ISSUE TITLE
Release Rust crate on crates.io

### ISSUE THREAD

**Issue by boxdot** [heremaps/flexible-polyline#17]
Right now, we are using flexpolyline as dependency directly from this repo with a hardcoded commit hash. We would like to use it from crates.io with proper versioning schema.

**Comment by boxdot** [comment]
@lene: Is there any problem with releasing it? I could take this issue.

**Comment by lene** [comment]
@boxdot There's already an OSS ticket to open a HERE account on crates.io, I'll message you the link on Teams.

**Comment by boxdot** [comment]
Discussed in person: I published the crate with maintainers @VeaaC and @gferon. When there is an official account from HERE, we will transform the ownership.

**Comment by boxdot** [comment]
Published. Invites out.
