### ISSUE TITLE
Pure Swift version

### ISSUE THREAD

**Issue by GerdC** [heremaps/flexible-polyline#18]
I translated the Java version into a pure Swift version and it works for me.
I'd spend it for this library, but I'm not experienced in creating a pull request.
Interested? How do you want it?

**Comment by macoapps** [comment]
Hi @GerdC ,
just starting with Here API in my Swift app. Is there any way to try your Swift implementation ?

**Comment by GerdC** [comment]
I posted the sourcecode of the poly line decoder here:
https://stackoverflow.com/questions/61481727/decoding-here-rest-api-polyline-in-swift

As of last year, if you want to use public transport, DO NOT use the HERE sdk, write the code yourself.
The polyline decoder is the hardest part, the rest is easy.

This is how my app looked over a year ago: https://attractions-map.com/en 
Ready to launch since then, but it does not make much sense to launch a tourist app during a pandemic
