### ISSUE TITLE
Cannot install with pip install flexipolyline

### ISSUE THREAD

**Issue by sariyadilak** [heremaps/flexible-polyline#19]
Hello 

I try to install flexipolyline in my computer, but there is error say

"ERROR: Could not find a version that satisfies the requirement flexipolyline (from versions: none)
ERROR: No matching distribution found for flexipolyline"

I also try 

python setup.py install
pip install -e .

it's still not work for me.
![2020-05-11_12-07-59](https://user-images.githubusercontent.com/35542691/81525826-1b386880-9380-11ea-98c7-cf52bcdc8a88.jpg)

**Comment by Thommynator** [comment]
Same issue for me.

**Comment by kalebinn** [comment]
Hi I hope this isn't too late for you - it may be helpful for others that eventually see this. The setup.py worked fine for me. Here are my steps:

1. Clone the repository 
2. Navigate to the repository: `/flexible-polyline/python` 
3. In your CLI type: `python setup.py install`

Your output should look like the following image: 

![image](https://user-images.githubusercontent.com/50221315/99332177-22b85d00-284e-11eb-895e-bf38af834b28.png)

**Comment by lene** [comment]
The `flexpolyline` package has been published on PyPI.
Install it with `$ pip install flexpolyline`. 
@sariyadilak Please note that it is spelled "flexpolyline", not "flexipolyline".
