### ISSUE TITLE
Compare with alternative tool/algorithm

### ISSUE THREAD

**Issue by deeplook** [heremaps/flexible-polyline#20]
I've discovered another tool which seems to be much related to this one. If so it might be worthwhile to write something in the README for its readers about if and how they compare:

https://developers.google.com/maps/documentation/utilities/polylinealgorithm

**Comment by VeaaC** [comment]
It could make sense to mention the benefits / differences somewhere in the README:
* flexible-polyline is URL safe
* flexible polyline allows for different precision of coordinates (and much higher ones)
* flexible polyline enables use of a 3rd dimension

**Comment by lene** [comment]
In the first section of the README is says exactly that:

> The encoding is a variant of [Encoded Polyline Algorithm Format](https://developers.google.com/maps/documentation/utilities/polylinealgorithm). The advantage of this encoding over the original are the following:
> 
> Output string is composed by only URL-safe characters, i.e. may be used without URL encoding as query parameters.
> Floating point precision is configurable: This allows to represent coordinates with precision up to microns (5 decimal places allow meter precision only).
> It allows to encode a 3rd dimension with a given precision, which may be a level, altitude, elevation or some other custom value.
>
