### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by deeplook** [heremaps/flexible-polyline#22]
Because now there is https://pypi.org/user/heremaps. See also https://github.com/heremaps/flexible-polyline/issues/8 and https://github.com/heremaps/flexible-polyline/issues/19.

**Comment by gacafe** [comment]
@deeplook can you explain how that resolves the problem... because I do not see this particular project is not on there - has it been absorbed into another project?

**Comment by deeplook** [comment]
https://github.com/heremaps/flexible-polyline/blob/master/python/README.md claims Flexpolyline can be installed for Python via `pip install flexpolyline` which implies that it is hosted on pypi.org which is not the case, see https://pypi.org/project/flexpolyline. If it was published there, e.g. with https://pypi.org/user/heremaps/ as maintainer, that command would actually work and the package could be imported/reused more easily in other packages like https://pypi.org/project/xyzspaces.

**Comment by lene** [comment]
Company internal process to publish to https://pypi.org/user/heremaps/ triggered.

**Comment by vojtamolda** [comment]
The "company internal process to publish" must be a huge behemoth since it's been running for more than a month and `pip install flexpolyline` is still broken...

**Comment by Thommynator** [comment]
@lene What's the current state of this process? Is there any update? 😃
Looks like it's still [not available on pypi.org](https://pypi.org/project/flexpolyline/). It would be really awesome if we could easily install it via pip. 🤩

**Comment by kalebinn** [comment]
> 
> 
> @lene What's the current state of this process? Is there any update? 😃
> Looks like it's still [not available on pypi.org](https://pypi.org/project/flexpolyline/). It would be really awesome if we could easily install it via pip. 🤩

Looks like its still not available on pypi.org but in the meantime you could use the following process to install flexpolyline: 
1. Clone the repository
2. Navigate to the repository: `/flexible-polyline/python`
3. In your CLI type: `python setup.py install`

**Comment by deeplook** [comment]
@kalebinn Yes, except that this doesn't work inside a `requirements.txt` file...

**Comment by lene** [comment]
The `flexpolyline` package has been published on PyPI.
Install it with `$ pip install flexpolyline`.
