### ISSUE TITLE
PHP implementation

### ISSUE THREAD

**Issue by roberto-butti** [heremaps/flexible-polyline#28]
Anyone is interested in PHP implementation?

I need to encode  polyline from Isoline API in PHP language.
I was thinking to plan and start to implement a encoder, but I found this repository.
My question is : is there something official for PHP ? Is there something reliable from community ?
If all answer are "no", I could plan to implement this.

Roberto

**Comment by VeaaC** [comment]
I am not aware of any PHP implementation yet

**Comment by roberto-butti** [comment]
I see now that there is a implementation via Pull request: https://github.com/heremaps/flexible-polyline/pull/21
I will take a look.
Roberto

**Comment by lene** [comment]
Closed by PR #21
