### ISSUE TITLE
Improve/replace C++ implementation

### ISSUE THREAD

**Issue by VeaaC** [heremaps/flexible-polyline#37]
The C++ implementation was one if the first, and by now is one older ones lacking a few things the other implementations have in common:
* running on the shared test set
* having an encode/decode command line CLI
* having warning-free code
* having polished API

Proposal: Replace current C++ implantation by just porting the Rust implementation 1:1

**Comment by lene** [comment]
I'm happy to approve this, if you find the time (or find someone who has the time) to do the porting :)

**Comment by devcooch** [comment]
@VeaaC is it done or not?

**Comment by VeaaC** [comment]
Yes @devcooch , this can be closed
