### ISSUE TITLE
Null Safety

### ISSUE THREAD

**Issue by flutteresbolivia** [heremaps/flexible-polyline#41]
when they release a new version it includes these new features from flutter 2.0
I use the package a lot

**Comment by JackofAllTradesDev** [comment]
Any updates on this? I need this a lot

**Comment by darwin-morocho** [comment]
> Any updates on this? I need this a lot

You can check the next PR https://github.com/heremaps/flexible-polyline/pull/43

**Comment by lene** [comment]
PR #43 is merged now, closing
