### ISSUE TITLE
Matlab version

### ISSUE THREAD

**Issue by RenoFilla** [heremaps/flexible-polyline#49]
Hi guys, 

Still waiting for any action re: pull request https://github.com/heremaps/flexible-polyline/pull/48

I actually now have also a function for *encoding* a flexpolyline in Matlab ([available here](https://se.mathworks.com/matlabcentral/fileexchange/101283-decode-and-encode-a-flexible-polyline-for-from-here-api)) but I will wait with offering it here on GitHub until above request has been approved. 

Cheers, Reno

**Comment by lene** [comment]
Sorry, GitHub did not send me any notifications for your further commits and comments on #48 , so I overlooked the progress you made. It is merged now. Thanks so much for your contribution!

**Comment by RenoFilla** [comment]
Thank you! Pull request https://github.com/heremaps/flexible-polyline/pull/50 is about the encoder and minor cosmetic changes in the decoding function. Test for encoding is also included. 

Cheers, Reno
