### ISSUE TITLE
Can't find @here/flexpolyline in npm registry

### ISSUE THREAD

**Issue by samzmann** [heremaps/flexible-polyline#5]
Hi there, wow, first issue in the repo!

I'm trying to install the node.js package with the command `yarn add @here/flexpolyline` and I get this error:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@here%2fflexpolyline: Not found".
```

Searching for "@here/flexpolyline" on npm.com returns nothing :/ So I'm guessing the package is not published yet. Or is it published somewhere else?

What is the expected use of this lib? Should I just copy the code from https://github.com/heremaps/flexible-polyline/blob/master/javascript/index.js into my own project?

Thanks!

**Comment by lene** [comment]
Hi! Yes, I am sorry, @here/flexpolyline is not yet published on npm.com. We are currently in the process of pushing it, but due to company policies that can take significantly longer than just running `npm publish`, I'm afraid.

In the meantime, yes, copying the code is the preferred way!

**Comment by LaVielle** [comment]
Oki doki, thanks.

**Comment by knownasilya** [comment]
Um, still not published.

**Comment by lene** [comment]
Reopening since yes, this should be done

**Comment by hanatharesh2712** [comment]
Please publish this package. really needed!

**Comment by olivercs** [comment]
I tried today but still not published. Any updates on this?

**Comment by Caerbannog** [comment]
In the meantime I have published the current master (71c34cb) here:
https://www.npmjs.com/package/@liberty-rider/flexpolyline

**Comment by hanatharesh2712** [comment]
@Caerbannog How can we use this package in Typescript? any minimum steps? thanks!

**Comment by mutantcornholio** [comment]
Still not there =)

**Comment by LaVielle** [comment]
Just contacted a friend who works at Here, maybe they can help getting this published 🤞

**Comment by niko-gardenanet** [comment]
Still not published!

**Comment by samzmann** [comment]
![image](https://github.com/heremaps/flexible-polyline/assets/22463797/07d992c0-937f-4e11-be23-94e7fcef6588)

**Comment by haraldF** [comment]
Until it's finally published, you can use a workaround via gitpkg:

```sh
npm install https://gitpkg.now.sh/heremaps/flexible-polyline/javascript
```

**Comment by haraldF** [comment]
It's published: https://www.npmjs.com/package/@here/flexpolyline

**Comment by allencoded** [comment]
This is not published. 

```
npm i @here/flexpolyline --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/@here%2fflexpolyline
npm ERR! 404
npm ERR! 404  '@here/flexpolyline@*' is not in this registry.
```

**Comment by VeaaC** [comment]
@allencoded it looks to me like you are using a npm mirror? Maybe that one does not contain the package. Can you try against the official repo?

**Comment by jesse-a-reilly** [comment]
> This is not published.
> 
> ```
> npm i @here/flexpolyline --save
> npm ERR! code E404
> npm ERR! 404 Not Found - GET https://repo.platform.here.com/artifactory/api/npm/maps-api-for-javascript/@here%2fflexpolyline
> npm ERR! 404
> npm ERR! 404  '@here/flexpolyline@*' is not in this registry.
> ```

I faced similar issues, even after checking NPM was using the default registry:
`npm set registry https://registry.npmjs.org/`

The solution I used was pulling from the Github repo, using [GitPkg](https://gitpkg.vercel.app/about/) to get the contents of the `/javascript` directory

This works, but two downsides are:

- You're relying on a random Vercel app, which may go down at any point
- You're pulling directly from the master branch, rather than pinning to a specific version
