### ISSUE TITLE
Is flexpolyline for Java published?

### ISSUE THREAD

**Issue by leslieli** [heremaps/flexible-polyline#55]
Hi there,

We would like to use flexpolyline in a Java project. However, once we added the following dependency to the `pom.xml`, it did not work. flexpolyline was not be loaded. Seem it isn't published yet. Could you please help confirm and suggest? 
```
<dependency>
      <groupId>com.here</groupId>
      <artifactId>flexpolyline</artifactId>
      <version>0.1.0</version>
    </dependency>
```
Should I just copy the code into our own project? 

Thanks!

**Comment by OrangeDog** [comment]
It doesn't appear in any major repositories, and there are no publishing settings in the code.

https://mvnrepository.com/artifact/com.here

The `<version>` is also out of date - the latest tag is `java-0.2.0`.

It would be good if this could be sorted out properly.

**Comment by cio** [comment]
As noted before, it is not published in maven repos and there are no immediate plans to change that although there would definitely be some use in that.
