### ISSUE TITLE
Is there a ruby version present?

### ISSUE THREAD

**Issue by domenik-b** [heremaps/flexible-polyline#57]
Hi all,

I would like to use flexible polyline decoding in ruby. Could anyone help? Is there a gem by any chance?

**Comment by VeaaC** [comment]
Hi @domenik-b . I can check if we have any Ruby experts in this project, but there is a good chance that there are none.

Out of curiosity: Would you be willing to work on an implementation? I could guide you through it (e.g. based on one of the other languages, or the spec itself). From my experience it doesn't take long to create an implementation as the format is rather simple.

**Comment by ProGM** [comment]
Hi @VeaaC, I've opened a PR (#58) adding a ruby implementation (starting from the python one).

**Comment by VeaaC** [comment]
Closing, the version was merged a while ago
