### ISSUE TITLE
Request to update the README.md of this Python section

### ISSUE THREAD

**Issue by kyooryoo** [heremaps/flexible-polyline#65]
I am Ling Jiang, the Platform Support Engineer in HERE.
This feedback is from the support case CS0092990.
The customer got confused as they cannot get the same encoded value from example:
https://developer.here.com/documentation/traffic-api/dev_guide/topics/concepts/geospatial-filters.html
Please update the README.md section by adding the **precision=6** or at least remind it.
As mentioned in the official document https://pypi.org/project/flexpolyline/

For your reference:
> print(fp.encode(example)) # this might be what the customer got by default.
BF81zgKsl1xCoUs7DojBrU0RgxC3N--C

> print(fp.encode(example, precision=6)) # this is what we provided in our example.
BG-6kmkDw1zwZqqG6xmBsgL5rGmwFgqZ_oEw1d

**Comment by VeaaC** [comment]
I would think that that should be documented in the traffic-api service you linked, not the in (generic) library that supports every possible precision?

**Comment by VeaaC** [comment]
Closing, as I mentioned this should be documented in the service that is using this format to expose same data.
